site_name: coala documentation
pages:
- Getting Started:
    - 'Introduction': 'README.md'
    - 'Installation': 'Install.md'
    - 'Tutorial': 'Tutorial.md'
    - 'Exit Codes': 'Exit_Codes.md'
- Getting Involved:
    - 'Introduction': 'Getting_Involved/README.md'
    - 'Writing Bears': 'Getting_Involved/Writing_Bears.md'
    - 'Review': 'Getting_Involved/Review.md'
    - 'Codestyle': 'Getting_Involved/Codestyle.md'
    - 'Executing Tests': 'Getting_Involved/Testing.md'
    - 'Writing Tests': 'Getting_Involved/Writing_Tests.md'
    - 'Translating': 'Getting_Involved/Translating.md'
    - 'Writing Good Commits': 'Getting_Involved/Writing_Good_Commits.md'
    - 'MAC Hints': 'Getting_Involved/MAC_Hints.md'
- General Developer Information:
    - 'A Hitchhikers Guide To Git (1): Genesis': 'General_Dev_Info/git_tutorial_1.md'
